// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTargetToGroup(arg1:string,arg2:string):Promise<string>;

export function BatchDeleteTargets(arg1:Array<string>):Promise<string>;

export function BatchScanTargets(arg1:Array<string>):Promise<string>;

export function CreateTargetGroup(arg1:string,arg2:Array<string>):Promise<string>;

export function DeleteFingerprint(arg1:string):Promise<string>;

export function DeletePOC(arg1:string):Promise<string>;

export function ExportResults(arg1:string,arg2:string):Promise<string>;

export function GenerateReport(arg1:string):Promise<string>;

export function GetAPIs():Promise<Record<string, string>>;

export function GetConfig():Promise<Record<string, any>>;

export function GetDictionaries():Promise<Record<string, string>>;

export function GetFingerprints():Promise<Array<string>>;

export function GetPOCs():Promise<Array<string>>;

export function GetResults(arg1:string):Promise<Record<string, any>>;

export function GetTargetGroups():Promise<Record<string, Array<string>>>;

export function GetTargets():Promise<Record<string, Record<string, any>>>;

export function GetTaskStatus(arg1:string):Promise<string>;

export function GetTaskTemplates():Promise<Array<string>>;

export function GetTasks():Promise<Record<string, Record<string, any>>>;

export function GetWorkflows():Promise<Record<string, Array<string>>>;

export function ImportTargets(arg1:string):Promise<string>;

export function LoadTaskTemplate(arg1:string):Promise<Record<string, any>>;

export function RemoveTargetFromGroup(arg1:string,arg2:string):Promise<string>;

export function RunScan(arg1:Array<string>,arg2:Record<string, any>):Promise<string>;

export function RunScanWithID(arg1:string,arg2:Array<string>,arg3:Record<string, any>):Promise<string>;

export function SaveAPI(arg1:string,arg2:string):Promise<string>;

export function SaveConfig(arg1:Record<string, any>):Promise<string>;

export function SaveDictionary(arg1:string,arg2:string):Promise<string>;

export function SaveTaskTemplate(arg1:string,arg2:Record<string, any>):Promise<string>;

export function TestFingerprint(arg1:string,arg2:string):Promise<string>;

export function TestPOC(arg1:string,arg2:string):Promise<string>;

export function UpdateWorkflow(arg1:string,arg2:Array<string>):Promise<string>;

export function UploadFingerprint(arg1:string):Promise<string>;

export function UploadPOC(arg1:string):Promise<string>;
