// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTargetToGroup(arg1, arg2) {
  return window['go']['main']['App']['AddTargetToGroup'](arg1, arg2);
}

export function BatchDeleteTargets(arg1) {
  return window['go']['main']['App']['BatchDeleteTargets'](arg1);
}

export function BatchScanTargets(arg1) {
  return window['go']['main']['App']['BatchScanTargets'](arg1);
}

export function CreateTargetGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateTargetGroup'](arg1, arg2);
}

export function DeleteFingerprint(arg1) {
  return window['go']['main']['App']['DeleteFingerprint'](arg1);
}

export function DeletePOC(arg1) {
  return window['go']['main']['App']['DeletePOC'](arg1);
}

export function ExportResults(arg1, arg2) {
  return window['go']['main']['App']['ExportResults'](arg1, arg2);
}

export function GenerateReport(arg1) {
  return window['go']['main']['App']['GenerateReport'](arg1);
}

export function GetAPIs() {
  return window['go']['main']['App']['GetAPIs']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetDictionaries() {
  return window['go']['main']['App']['GetDictionaries']();
}

export function GetFingerprints() {
  return window['go']['main']['App']['GetFingerprints']();
}

export function GetPOCs() {
  return window['go']['main']['App']['GetPOCs']();
}

export function GetResults(arg1) {
  return window['go']['main']['App']['GetResults'](arg1);
}

export function GetTargetGroups() {
  return window['go']['main']['App']['GetTargetGroups']();
}

export function GetTargets() {
  return window['go']['main']['App']['GetTargets']();
}

export function GetTaskStatus(arg1) {
  return window['go']['main']['App']['GetTaskStatus'](arg1);
}

export function GetTaskTemplates() {
  return window['go']['main']['App']['GetTaskTemplates']();
}

export function GetTasks() {
  return window['go']['main']['App']['GetTasks']();
}

export function GetWorkflows() {
  return window['go']['main']['App']['GetWorkflows']();
}

export function ImportTargets(arg1) {
  return window['go']['main']['App']['ImportTargets'](arg1);
}

export function LoadTaskTemplate(arg1) {
  return window['go']['main']['App']['LoadTaskTemplate'](arg1);
}

export function RemoveTargetFromGroup(arg1, arg2) {
  return window['go']['main']['App']['RemoveTargetFromGroup'](arg1, arg2);
}

export function RunScan(arg1, arg2) {
  return window['go']['main']['App']['RunScan'](arg1, arg2);
}

export function RunScanWithID(arg1, arg2, arg3) {
  return window['go']['main']['App']['RunScanWithID'](arg1, arg2, arg3);
}

export function SaveAPI(arg1, arg2) {
  return window['go']['main']['App']['SaveAPI'](arg1, arg2);
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveDictionary(arg1, arg2) {
  return window['go']['main']['App']['SaveDictionary'](arg1, arg2);
}

export function SaveTaskTemplate(arg1, arg2) {
  return window['go']['main']['App']['SaveTaskTemplate'](arg1, arg2);
}

export function TestFingerprint(arg1, arg2) {
  return window['go']['main']['App']['TestFingerprint'](arg1, arg2);
}

export function TestPOC(arg1, arg2) {
  return window['go']['main']['App']['TestPOC'](arg1, arg2);
}

export function UpdateWorkflow(arg1, arg2) {
  return window['go']['main']['App']['UpdateWorkflow'](arg1, arg2);
}

export function UploadFingerprint(arg1) {
  return window['go']['main']['App']['UploadFingerprint'](arg1);
}

export function UploadPOC(arg1) {
  return window['go']['main']['App']['UploadPOC'](arg1);
}
